version: '3.4'

services:
  db:
    image: fiap-webservices-restful-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: webservices_restful_technologies
    ports:
      - 3308:3306
    networks:
      - fiap-network
      
  fiap-webservices-restful:
    image: fiap-webservices-restful
    build:
      context: .
      dockerfile: FiapWebservicesRestfulTechnologies/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80
    depends_on:
      - db
    networks:
      - fiap-network
networks:
  fiap-network:
    driver: bridge
    
